[package]
name = "nexus-default-programs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "c2pa"
path = "c2pa.rs"

[dependencies]
risc0-zkvm = { version = "0.19", default-features = false }

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = true
panic = 'abort'
incremental = false
codegen-units = 1
rpath = false 