[package]
name = "nexus-default-programs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "c2pa"
path = "c2pa.rs"

[dependencies]
risc0-zkvm = { version = "0.19", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
hex = { version = "0.4", default-features = false, features = ["alloc"] }

[dev-dependencies]
ed25519-dalek = "1.0"
rand = "0.7"

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = true
panic = 'abort'
incremental = false
codegen-units = 1
rpath = false

[features]
default = ["std"]
std = [
    "serde/std",
    "serde_json/std",
    "hex/std",
] 