[package]
name = "c2pa-core"
version = "0.1.0"
edition = "2021"

[features]
default = ["pure-rust"]
pure-rust = []
zkvm = []

[dependencies]
ed25519-dalek = { version = "2.1.0", default-features = false }
cfg-if = "1.0"

[dev-dependencies]
test-case = "3.3.1"
rand = "0.8" 