[package]
name = "c2pa"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
nexus-rt = { workspace = true }
nexus-sdk = { workspace = true }
libm = { workspace = true }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = "z"
lto = true
codegen-units = 1
strip = true 