[package]
name = "c2pa-core"
version.workspace = true
edition.workspace = true

[dependencies]
nexus-sdk = { workspace = true }

[dev-dependencies]
nexus-sdk = { workspace = true, features = ["host"] }
test-case = "3.3.1" 