[build]
target = "riscv32im-unknown-none-elf"

[target.riscv32im-unknown-none-elf]
rustflags = [
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=--gc-sections",
]

[unstable]
build-std = ["core", "alloc"]
build-std-features = ["compiler-builtins-mem"] 