[workspace]
resolver = "2"
members = [
    "c2pa",
]

[workspace.package]
edition = "2021"
version = "0.1.0"
authors = ["The Nexus Team <hello@nexus.xyz>"]
homepage = "https://nexus.xyz/"
keywords = ["nexus", "zero-knowledge", "zkvm", "cryptography", "proofs"]
categories = ["cryptography"]
publish = false

[workspace.dependencies]
nexus-rt = { git = "https://github.com/nexus-xyz/nexus-zkvm", tag = "0.3.2", default-features = false, features = ["minimal"] }
nexus-sdk = { git = "https://github.com/nexus-xyz/nexus-zkvm", tag = "0.3.2", default-features = false, features = ["minimal"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
uuid = { version = "1.16.0", features = ["js", "v4"], default-features = false }

[patch.crates-io]
uuid = { version = "1.16.0", default-features = false } 