name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  build:
    name: Build, Test and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            clients/cli
            proto

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: ./clients/cli

      - name: Install Protobuf Compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Check formatting
        working-directory: clients/cli
        run: |
          cargo fmt --all -- --check

      - name: Build
        working-directory: clients/cli
        run: |
          cargo build --profile=ci-build

      - name: Run clippy
        working-directory: clients/cli
        run: |
          cargo clippy --profile=ci-build --all-targets --all-features -- -D warnings

      - name: Run tests
        working-directory: clients/cli
        run: |
          cargo test --profile=ci-build --all-features --all-targets

      - name: Check for uncommitted changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then \
              echo "There are uncommitted changes in working tree after building."; \
              git status; \
              git --no-pager diff; \
              exit 1; \
          else \
              echo "Git working tree is clean"; \
          fi;
